version: '2'

services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ${PATH_NGINX_CERTS}:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-gen:
    restart: always
    image: bingozb/nginx-gen
    container_name: nginx-gen
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  nginx-certbot:
    restart: always
    image: bingozb/nginx-certbot
    container_name: nginx-certbot
    volumes_from:
      - nginx
    volumes:
      - ${PATH_NGINX_CERTS}:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro